name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Semantic version (major | minor | patch | premajor | preminor | prepatch | prerelease)'
        default: 'patch'
        required: true
        
jobs:
  version:
    name: Create version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
        scope: '@darkroom-com'
    - run: npm install
    - run: npm pack
    - uses: actions/upload-artifact@v2
      with:
        name: npm
        path: "*.tgz"
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
